# Covid_ODE model configuration

data:
  mobility_matrix: data/example_mobility.csv
  population_size: data/example_population.csv
  commute_volume: data/example_traffic_flow.csv
  reported_cases: data/example_cases.csv

parameter:
  beta1: 0.6    # R0 2.4
  beta2: 0.5   # Contact with commuters 1/3rd of the time
  beta3: 1.0    # lockdown vs normal
  nu: 0.5      # E -> I transition rate
  gamma: 0.25   # I -> R transition rate

mcmc:
  dmax: 21
  nmax: 50
  m: 1
  occult_nmax: 15
  num_event_time_updates: 5
  num_bursts: 10
  num_burst_samples: 100
  thin: 1
  
output:
  posterior: example_posterior.h5

