# Covid_ODE model configuration

data:
  mobility_matrix: data/mergedflows.csv
  population_size: data/c2019modagepop.csv
  commute_volume: data/example_flow.csv
  reported_cases: data/example_cases.csv
  total_tests: data/example_num_tested.csv
  case_date_type: specimen
  pillar: "1"
  npi: data/example_npi.csv

settings:
  inference_period:
    - 2020-09-04
    - 2020-11-27
  time_step: 1.

mcmc:
  dmax: 84
  nmax: 50
  m: 1
  occult_nmax: 15
  num_event_time_updates: 35
  num_bursts: 10
  num_burst_samples: 20
  thin: 1
  prior:
    gamma:
      concentration: 2.0
      rate: 4.0

output:
  results_dir: './'
  posterior: posterior.hd5
  national_rt: national_rt.xlsx
  geopackage: prediction.gpkg
