# Covid_ODE model configuration

data:
  mobility_matrix: /home/jewellcp/Insync/jewellcp@lancaster.ac.uk/OneDrive Biz - Shared/covid19/data/UK_Commute_2019/mergedflows.csv
  population_size: /home/jewellcp/Insync/jewellcp@lancaster.ac.uk/OneDrive Biz - Shared/covid19/data/UK_Commute_2019/c2019modagepop.csv
  commute_volume: /home/jewellcp/Insync/jewellcp@lancaster.ac.uk/OneDrive Biz - Shared/covid19/data/DfT/2020-10-16/201016_OFF_SEN_COVID19_road_traffic_national_table.xlsx

settings:
  inference_period:
    - 2020-07-24
    - 2020-10-16
  time_step: 1.
  prediction_period:
    - 2020-02-19
    - 2020-08-01

mcmc:
  dmax: 21
  nmax: 50
  m: 1
  occult_nmax: 5
  num_event_time_updates: 35
  num_bursts: 100
  num_burst_samples: 100
  thin: 1
  
output:
  results_dir: output/2020-10-16_1_specimen
  posterior: posterior.hd5
  national_rt: national_rt.xlsx
  medium_term: medium_term.xlsx
  geopackage: prediction.gpkg
